# Generated by Django 5.1.6 on 2025-02-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_enrollment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enrollment',
            table='enrollments',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
